---
name: Draft Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release/*
  pull_request:
    branches:
      - main
    types:
      - ready_for_review
  workflow_dispatch:

jobs:
  create-pr:
    name: Create PR
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.get-tag.outputs.release-tag }}
    steps:
      - name: Log GitHub Context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo -e "\`\`\`json\n$GITHUB_CONTEXT\n\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Get Release Tag
        id: get-tag
        # yamllint disable rule:line-length
        env:
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          release_tag=$(echo "$BRANCH_NAME" | cut -d '/' -f2)

          if ! [[ $release_tag =~ ^[0-9]{1,2}\.[0-9]{1,4}\.[0-9]{1,4}$ ]]
          then
              echo "Release number is invalid: \`$release_tag\`" >> $GITHUB_STEP_SUMMARY
              exit 1
          fi

          echo "release-tag=$release_tag" >> $GITHUB_OUTPUT
        # yamllint enable rule:line-length

      - name: Check If PR Exists
        id: check-if-pr-exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          existing_pr=$(
            gh pr list \
            --repo ${{ github.repository }} \
            --json baseRefName,headRefName,title \
            --jq '
              .[] | select(
                .baseRefName == "main"
              ) | select(
                .headRefName == "release/${{ steps.get-tag.outputs.release-tag }}"
              )
            '
          )

          if [[ -z "$existing_pr" ]]; then
              echo "create-pr=true" >> $GITHUB_OUTPUT
          else
              echo -e "Existing PR found: \`\`\`json" >> $GITHUB_STEP_SUMMARY
              echo "$("$existing_pr" | jq --color-output)" >> $GITHUB_STEP_SUMMARY
              echo -e "\`\`\`" >> $GITHUB_STEP_SUMMARY
              echo "create-pr=false" >> $GITHUB_OUTPUT
          fi

      - name: Clone Repo
        if: steps.check-if-pr-exists.outputs.create-pr == 'true'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

      - name: Create PR
        if: steps.check-if-pr-exists.outputs.create-pr == 'true'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --repo ${{ github.repository }} \
            --title "Release ${{ steps.get-tag.outputs.release-tag }}" \
            --fill \
            --base main \
            --head release/${{ steps.get-tag.outputs.release-tag }} \
            --reviewer ${{ github.repository_owner }} \
            --draft

  draft-release:
    name: Draft Release
    needs:
      - create-pr
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

      - name: Validate `pyproject.toml` version
        # yamllint disable rule:line-length
        run: |
          expected_line="version = \"${{ needs.create-pr.outputs.release-tag }}\""
          actual_line=$(grep -E "^version = \"" pyproject.toml)
          if [ "$expected_line" != "$actual_line" ]
          then
              echo "`pyproject.toml` version is invalid: \`$actual_line\`" >> $GITHUB_STEP_SUMMARY
              exit 1
          fi
        # yamllint enable rule:line-length

      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.WORGARSIDE_DEV_TOKEN }}

  build-and-add-to-notes:
    name: Build and Add to Release Notes
    needs:
      - create-pr
      - draft-release
    uses: worgarside/wg-utilities/.github/workflows/build_and_publish.yml@develop
    with:
      build_branch: ${{ github.head_ref || github.ref_name }}
      environment: development
      release_tag: ${{ needs.create-pr.outputs.release-tag }}
    secrets: inherit
